name: Lint and Test

on: [pull_request, push]

jobs:
  build:
    name: Build 🔧
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: npm install
      - name: Build bundle
        run: npm run build
  lint:
    name: Lint 🧹
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Run linter
        run: npm run lint
      - name: Run tests
        run: npm run test
  test:
    name: Test 🧪
    runs-on: ubuntu-latest
    needs: [build, lint]
    steps:
      - name: Run tests
        run: npm run test